version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies- # fallback to using the latest cache if no exact match is found

      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Trigger build
          command: npm run build:mta

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
       
      - persist_to_workspace:
          root: ~/repo
          paths: .

  github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish Release on GitHub
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Auto-publish version ${VERSION}" -c ${CIRCLE_SHA1} -delete ${VERSION} ./mta_archives/city-explorer-demo-app_${VERSION}.mtar 

workflows:
  version: 2
  test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^.*/
      - github-release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
